"""Child-friendly content for Future Money Quest."""

PRODUCTS = {
    "cash": {
        "name": "現金・預金",
        "emoji": "🪙",
        "color": "#55B6A8",
        "risk": "小さい",
        "story": "すぐ使える『お金の水筒』。急な出費のときに役立つよ。",
        "detail": "値段はほとんど動きません。その代わり、大きく増えにくく、物価が上がると買える物が減ることがあります。",
        "nisa": "対象外。預金はNISAで買う金融商品ではありません。",
    },
    "bond": {
        "name": "債券・バランス投信",
        "emoji": "🛟",
        "color": "#78A7E8",
        "risk": "小～中",
        "story": "国や会社にお金を貸したり、株と債券をまぜる『ゆれを小さくする船』。",
        "detail": "株より値動きが小さい傾向ですが、金利や発行元の状態で損をすることもあります。バランス投信は複数の資産をひとまとめにします。",
        "nisa": "金融庁の条件を満たす投資信託なら対象になり得ます。商品ごとの確認が必要です。",
    },
    "index": {
        "name": "世界株インデックス",
        "emoji": "🌏",
        "color": "#66BE73",
        "risk": "中",
        "story": "世界中のたくさんの会社を少しずつ集めた『会社の詰め合わせパック』。",
        "detail": "1社だけに賭けず分散できます。世界の会社が成長すれば増える可能性がありますが、不況では大きく下がる年もあります。",
        "nisa": "金融庁の条件を満たす長期・積立・分散向け投資信託なら対象になり得ます。",
    },
    "stock": {
        "name": "個別株",
        "emoji": "🏢",
        "color": "#FFB64D",
        "risk": "大きい",
        "story": "応援したい1つの会社の『小さなオーナー券』を持つイメージ。",
        "detail": "会社が伸びると大きく増えることがありますが、失敗すると大きく減ることも。会社を調べる力と分散が大切です。",
        "nisa": "このゲームが扱う0～17歳のつみたて枠では対象外として扱います。",
    },
    "challenge": {
        "name": "暗号資産・FX",
        "emoji": "🎢",
        "color": "#E8718D",
        "risk": "とても大きい",
        "story": "上にも下にも速く動く『ジェットコースター』。なくなって困るお金は乗せないでね。",
        "detail": "短期間で大きく増減し、元本を失うことがあります。FXは取引方法によって預けた額以上の損失もあり得ます。",
        "nisa": "対象外。暗号資産とFXはNISA商品ではありません。",
    },
}


# Salary values use units of 万円. ``salary`` is the public reference figure,
# while ``starting_salary`` is a conservative first-year learning model.  The
# simulation moves from the first-year value toward the public reference as
# experience grows; it never treats the all-age average as a starting salary.
# Probabilities are explicitly game parameters, not employment statistics.
CAREERS = [
    {
        "key": "programmer",
        "name": "AI・プログラマー",
        "emoji": "💻",
        "salary": 578.5,
        "starting_salary": 360,
        "average_age": 37.1,
        "years_to_average": 15,
        "salary_source": "厚生労働省 job tag（プログラマー・令和7年調査）",
        "salary_url": "https://shigoto.mhlw.go.jp/User/Occupation/Detail/313",
        "salary_note": "就職1年目は大卒初任給とIT職の公開賃金を基にした学習用モデル。",
        "probability": 55,
        "skills": "算数・英語・コードで作る練習",
        "message": "コンピューターにお願いする言葉を書き、便利な仕組みを作る仕事。",
    },
    {
        "key": "game_creator",
        "name": "ゲームクリエイター",
        "emoji": "🎮",
        "salary": 583.3,
        "starting_salary": 330,
        "average_age": 41.7,
        "years_to_average": 20,
        "salary_source": "厚生労働省 job tag（ゲームクリエーター・令和7年調査）",
        "salary_url": "https://shigoto.mhlw.go.jp/User/Occupation/Detail/330",
        "salary_note": "企画・CG・開発など職種差が大きいため、就職1年目は控えめな学習用モデル。",
        "probability": 35,
        "skills": "企画・絵・音・プログラミング",
        "message": "遊ぶ人をワクワクさせる世界とルールを、チームで作る仕事。",
    },
    {
        "key": "doctor",
        "name": "医師",
        "emoji": "🩺",
        "salary": 1512.3,
        "starting_salary": 600,
        "average_age": 45.7,
        "years_to_average": 20,
        "salary_source": "厚生労働省 job tag（内科医・令和7年調査）",
        "salary_url": "https://shigoto.mhlw.go.jp/User/Occupation/Detail/404",
        "salary_note": "研修医・勤務医を想定。診療科、当直、勤務先、開業の有無で大きく変わります。",
        "probability": 12,
        "skills": "理科・長い学習・人を思う力",
        "message": "病気やけがを調べ、治療して人の命と健康を支える仕事。",
    },
    {
        "key": "vet",
        "name": "獣医師",
        "emoji": "🐾",
        "salary": 680.5,
        "starting_salary": 360,
        "average_age": 38.7,
        "years_to_average": 14,
        "salary_source": "厚生労働省 job tag（獣医師・令和7年調査）",
        "salary_url": "https://shigoto.mhlw.go.jp/User/Occupation/Detail/223",
        "salary_note": "動物病院、公務員、企業など勤務先による差を単純化した学習用モデル。",
        "probability": 15,
        "skills": "生物・長い学習・動物への責任",
        "message": "動物の病気を治し、人と動物が元気に暮らせるよう助ける仕事。",
    },
    {
        "key": "architect",
        "name": "建築士",
        "emoji": "🏠",
        "salary": 679.1,
        "starting_salary": 360,
        "average_age": 43.4,
        "years_to_average": 20,
        "salary_source": "厚生労働省 job tag（建築設計技術者・令和7年調査）",
        "salary_url": "https://shigoto.mhlw.go.jp/User/Occupation/Detail/20",
        "salary_note": "資格、設計分野、会社規模による差を単純化した学習用モデル。",
        "probability": 30,
        "skills": "算数・図工・安全を考える力",
        "message": "家や建物を、安全で使いやすくなるよう設計する仕事。",
    },
    {
        "key": "teacher",
        "name": "先生・保育の仕事",
        "emoji": "🧑‍🏫",
        "salary": 442.6,
        "starting_salary": 320,
        "average_age": 39.1,
        "years_to_average": 17,
        "salary_source": "厚生労働省 job tag（幼稚園教員・令和7年調査）",
        "salary_url": "https://shigoto.mhlw.go.jp/User/Occupation/Detail/178",
        "salary_note": "幼稚園教員を代表例にしたモデル。学校種、公立・私立、勤続年数で変わります。",
        "probability": 45,
        "skills": "伝える力・聞く力・資格の勉強",
        "message": "子どもの発見や成長に寄り添い、学ぶ楽しさを届ける仕事。",
    },
    {
        "key": "patissier",
        "name": "パティシエ",
        "emoji": "🧁",
        "salary": 396.7,
        "starting_salary": 280,
        "average_age": 43.5,
        "years_to_average": 22,
        "salary_source": "厚生労働省 job tag（洋菓子製造、パティシエ・令和7年調査）",
        "salary_url": "https://shigoto.mhlw.go.jp/User/Occupation/Detail/3",
        "salary_note": "勤務先、役職、独立の有無による差を単純化した学習用モデル。",
        "probability": 50,
        "skills": "料理・衛生・くり返し練習",
        "message": "お菓子のおいしさと見た目で、特別な時間を作る仕事。",
    },
    {
        "key": "illustrator",
        "name": "イラストレーター",
        "emoji": "🎨",
        "salary": 492.2,
        "starting_salary": 300,
        "average_age": 39.8,
        "years_to_average": 18,
        "salary_source": "厚生労働省 job tag（イラストレーター・令和7年調査）",
        "salary_url": "https://shigoto.mhlw.go.jp/User/Occupation/Detail/342",
        "salary_note": "会社員を中心にしたモデル。フリーランスの収入変動は反映していません。",
        "probability": 30,
        "skills": "観察・描く練習・作品集づくり",
        "message": "絵で物語や情報を伝え、本・広告・ゲームなどを彩る仕事。",
    },
    {
        "key": "video_creator",
        "name": "動画クリエイター",
        "emoji": "🎬",
        "salary": 583.3,
        "starting_salary": 320,
        "average_age": 41.7,
        "years_to_average": 20,
        "salary_source": "厚生労働省 job tag（動画制作・令和7年調査）",
        "salary_url": "https://shigoto.mhlw.go.jp/User/Occupation/Detail/328",
        "salary_note": "会社員を中心にしたモデル。配信収入やフリーランスの大きな変動は含みません。",
        "probability": 20,
        "skills": "企画・撮影・編集・発信のルール",
        "message": "映像と音で、人に分かりやすく楽しい物語を届ける仕事。",
    },
    {
        "key": "athlete",
        "name": "プロスポーツ選手",
        "emoji": "⚽",
        "salary": 480,
        "starting_salary": 360,
        "average_age": 27.0,
        "years_to_average": 5,
        "salary_model": "athlete",
        "salary_source": "Jリーグ（2026/27シーズンのJ1基本報酬下限を参考）",
        "salary_url": "https://www.jleague.jp/news/article/28943/",
        "salary_note": "競技・リーグ・成績で差が極端に大きいため、Jリーグの下限を参考にした学習用モデル。35歳以降はスポーツ関連職への転身を想定。",
        "probability": 3,
        "skills": "体づくり・技術・休む力・継続",
        "message": "高い技術で競い、観る人に勇気や感動を届ける仕事。",
    },
]


EVENTS = [
    {
        "min_age": 0,
        "max_age": 12,
        "title": "おこづかいをどうする？",
        "description": "お祝いで2万円をもらったよ。いまの楽しみと未来、どう分ける？",
        "options": [
            {"key": "toy", "label": "ほしい物に2万円使う", "cost": 2, "happiness": 7, "knowledge": 1, "lesson": "楽しく使うのもお金の役目。使う前に残りを考えよう。"},
            {"key": "split", "label": "半分使い、半分残す", "cost": 1, "happiness": 5, "knowledge": 4, "lesson": "今と未来の両方に分ける方法があるね。"},
            {"key": "save", "label": "全部、未来のために残す", "cost": 0, "happiness": 2, "knowledge": 3, "lesson": "時間を味方にできるけれど、今の楽しみとのバランスも大切。"},
        ],
    },
    {
        "min_age": 13,
        "max_age": 17,
        "title": "新しいスマホがほしい！",
        "description": "友だちの最新機種はかっこいい。10万円を全部使う？工夫する？",
        "options": [
            {"key": "phone_new", "label": "最新機種を買う（10万円）", "cost": 10, "happiness": 8, "knowledge": 1, "lesson": "満足は得られるけれど、未来に回るお金は減るよ。"},
            {"key": "phone_used", "label": "中古を買う（4万円）", "cost": 4, "happiness": 5, "knowledge": 4, "lesson": "目的を満たしながら支出を抑えるのも立派な工夫。"},
            {"key": "phone_keep", "label": "今の機種を使い続ける", "cost": 0, "happiness": 1, "knowledge": 4, "lesson": "買わないという選択は、未来の選択肢を残すよ。"},
        ],
    },
    {
        "min_age": 18,
        "max_age": 29,
        "title": "社会人の暮らしを選ぼう",
        "description": "便利で広い部屋と、少し遠いコンパクトな部屋。固定費は毎年続くよ。",
        "options": [
            {"key": "home_big", "label": "駅近の広い部屋（追加30万円）", "cost": 30, "happiness": 9, "knowledge": 1, "lesson": "毎月の固定費は小さく見えても、長い期間では大きくなるよ。"},
            {"key": "home_balance", "label": "便利さと家賃のバランス（15万円）", "cost": 15, "happiness": 6, "knowledge": 3, "lesson": "値段だけでなく、時間や便利さも比べて決めよう。"},
            {"key": "home_small", "label": "家賃を抑える（5万円）", "cost": 5, "happiness": 3, "knowledge": 5, "lesson": "固定費を抑えると、未来に回すお金を作りやすい。"},
        ],
    },
    {
        "min_age": 30,
        "max_age": 44,
        "title": "もしもの備えを考えよう",
        "description": "突然40万円が必要に。予備の現金が少ないと、投資を急いで売るか借りることになるよ。",
        "options": [
            {"key": "emergency", "label": "予備費から40万円払う", "cost": 40, "happiness": -2, "knowledge": 5, "lesson": "現金は、値下がり中の投資を売らずに済むクッション。"},
            {"key": "insurance", "label": "必要な保険を使い15万円払う", "cost": 15, "happiness": 0, "knowledge": 4, "lesson": "起きると困る大きな損失には、必要な範囲で備える方法がある。"},
            {"key": "borrow", "label": "今は5万円払い、残りは借りる", "cost": 5, "debt": 35, "happiness": 1, "knowledge": 2, "lesson": "借金には利息がつく。返せる計画と総額の確認が必要だよ。"},
        ],
    },
    {
        "min_age": 45,
        "max_age": 54,
        "title": "学び直しか、今のままか",
        "description": "仕事の道具が変化した。新しい技術を学ぶと、できることが増えそう。",
        "options": [
            {"key": "reskill", "label": "20万円で学び直す", "cost": 20, "happiness": 3, "knowledge": 8, "lesson": "自分への投資は、未来の仕事や選択肢を増やすことがある。"},
            {"key": "free_learn", "label": "無料教材で少しずつ学ぶ", "cost": 0, "happiness": 1, "knowledge": 5, "lesson": "お金をかけなくても、時間と工夫で学べる。"},
            {"key": "no_learn", "label": "いまの方法を続ける", "cost": 0, "happiness": 2, "knowledge": 1, "lesson": "変えない安心もあるけれど、環境の変化は確認しよう。"},
        ],
    },
    {
        "min_age": 55,
        "max_age": 65,
        "title": "『必ず2倍』の投資話",
        "description": "SNSの人が『絶対に損しない。今日だけ』とすすめてきたよ。",
        "options": [
            {"key": "scam", "label": "40万円を渡す", "cost": 40, "happiness": -8, "knowledge": 0, "lesson": "『必ず』『今だけ』は危険信号。利益の保証はできないよ。"},
            {"key": "ask", "label": "家族や公的窓口に相談する", "cost": 0, "happiness": 3, "knowledge": 8, "lesson": "一人で即決せず、信頼できる情報を確かめるのが防御になる。"},
            {"key": "block", "label": "断ってブロックする", "cost": 0, "happiness": 2, "knowledge": 6, "lesson": "うますぎる話から離れるのも、お金を守る大切な行動。"},
        ],
    },
]


QUIZZES = [
    {
        "question": "100円を毎月ためるのと、気が向いた月だけためるのでは、続けやすいのは？",
        "options": ["毎月、自動でためる", "気が向いた月だけ", "どちらも必ず同じ"],
        "correct": 0,
        "explanation": "先に決めて自動で積み立てると、使う前に未来分を残しやすいよ。",
    },
    {
        "question": "1つの会社だけでなく、たくさんの会社に分けて投資する考え方は？",
        "options": ["集中", "分散", "借金"],
        "correct": 1,
        "explanation": "分散は、1つがうまくいかないときの影響を小さくする考え方。",
    },
    {
        "question": "値段が下がった資産を売り、上がった資産を買うのがリバランス？",
        "options": ["はい", "いいえ。目標の割合に戻すこと", "必ず全部売ること"],
        "correct": 1,
        "explanation": "リバランスは、増減してずれた配分を最初に決めた割合へ戻すこと。",
    },
    {
        "question": "一般に、大きく増える可能性がある商品はどうなる？",
        "options": ["大きく減る可能性もある", "必ず増える", "値段が動かない"],
        "correct": 0,
        "explanation": "高いリターンの可能性と、大きく損する可能性はセットだよ。",
    },
    {
        "question": "『元本保証で必ず2倍』と言われたら？",
        "options": ["すぐ買う", "借りて増やす", "断り、信頼できる人や公的情報で確認"],
        "correct": 2,
        "explanation": "『必ず』『今だけ』と急がせる話は、まず距離を取って確認しよう。",
    },
]


def event_for_age(age: int) -> dict:
    """Return the age-appropriate event."""
    return next(item for item in EVENTS if item["min_age"] <= age <= item["max_age"])


def career_by_key(key: str) -> dict:
    return next(item for item in CAREERS if item["key"] == key)
